version: '3'
services:
  redis-sentinel:
    build: .
    volumes:
      - ./:/root/redis
    working_dir: /root/redis/redis-sentinel
    command: 'bash run.sh'
    ports:
      - "7000:7000"
      - "7001:7001"
      - "7002:7002"
      - "26379:26379"
      - "26380:26380"
      - "26381:26381"  
    networks:
      mynet:
        ipv4_address: 172.25.1.102
  redis-cluster:
    build: .
    volumes:
      - ./:/root/redis
    working_dir: /root/redis/redis-cluster
    command: 'bash run.sh'
    ports:
      - "7000:7000"
      - "7001:7001"
      - "7002:7002"
      - "7003:7003"
      - "7004:7004"
      - "7005:7005"  
    networks:
      mynet:
        ipv4_address: 172.25.1.103               
networks:
  mynet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.1.0/24
